name: Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GCC_VERSION: "15.2.0"
  GCC_SHA256: "7294d65cc1a0558cb815af0ca8c7763d86f7a31199794ede3f630c0d1b0a5723"
  MAKE_VERSION: "4.4.1"
  MAKE_SHA256: "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
  LINUX_HEADERS_VERSION: "6.12.43"
  LINUX_HEADERS_SHA256: "33240edd67f6842a0bd672e8a60ee5668ef4b4a79370cfd0c5af901ecee34aa4"
  BINUTILS_VERSION: "2.45"
  BINUTILS_SHA256: "8a3eb4b10e7053312790f21ee1a38f7e2bbd6f4096abb590d3429e5119592d96"
  ZLIB_VERSION: "1.3.1"
  ZLIB_SHA256: "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"
  OPENSSL_VERSION: "3.5.2"
  OPENSSL_SHA256: "c53a47e5e441c930c3928cf7bf6fb00e5d129b630e0aa873b08258656e7345ec"
  CURL_VERSION: "8.15.0"
  CURL_SHA256: "d85cfc79dc505ff800cb1d321a320183035011fa08cb301356425d86be8fc53c"
  GIT_VERSION: "2.51.0"
  GIT_SHA256: "3d531799d2cf2cac8e294ec6e3229e07bfca60dc6c783fe69e7712738bef7283"
  CMAKE_VERSION: "4.1.0"
  CMAKE_SHA256: "81ee8170028865581a8e10eaf055afb620fa4baa0beb6387241241a975033508"
  PYTHON_VERSION: "3.13.7"
  PYTHON_SHA256: "6c9d80839cfa20024f34d9a6dd31ae2a9cd97ff5e980e969209746037a5153b2"

jobs:
  base-build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.arch }}/Dockerfile.base
          platforms: linux/${{ matrix.arch }}
          build-args: |
            GCC_VERSION=${{ env.GCC_VERSION }}
            GCC_SHA256=${{ env.GCC_SHA256 }}
            MAKE_VERSION=${{ env.MAKE_VERSION }}
            MAKE_SHA256=${{ env.MAKE_SHA256 }}
            LINUX_HEADERS_VERSION=${{ env.LINUX_HEADERS_VERSION }}
            LINUX_HEADERS_SHA256=${{ env.LINUX_HEADERS_SHA256 }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            BINUTILS_SHA256=${{ env.BINUTILS_SHA256 }}
          outputs: type=image,name=zhongruoyu/buildpack-deps,name-canonical=true,push=true,push-by-digest=true
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP"/digests/"$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          ARCH: ${{ matrix.arch }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-base-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*

  base-merge:
    needs: base-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-base-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create \
            --tag=zhongruoyu/buildpack-deps:base \
            zhongruoyu/buildpack-deps@sha256:"$(cat "$RUNNER_TEMP"/digests/x86_64)" \
            zhongruoyu/buildpack-deps@sha256:"$(cat "$RUNNER_TEMP"/digests/aarch64)"

  extended-build:
    needs: base-merge
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.arch }}/Dockerfile.extended
          platforms: linux/${{ matrix.arch }}
          build-args: |
            ZLIB_VERSION=${{ env.ZLIB_VERSION }}
            ZLIB_SHA256=${{ env.ZLIB_SHA256 }}
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}
            OPENSSL_SHA256=${{ env.OPENSSL_SHA256 }}
            CURL_VERSION=${{ env.CURL_VERSION }}
            CURL_SHA256=${{ env.CURL_SHA256 }}
            GIT_VERSION=${{ env.GIT_VERSION }}
            GIT_SHA256=${{ env.GIT_SHA256 }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            CMAKE_SHA256=${{ env.CMAKE_SHA256 }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_SHA256=${{ env.PYTHON_SHA256 }}
          outputs: type=image,name=zhongruoyu/buildpack-deps,name-canonical=true,push=true,push-by-digest=true
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP"/digests/"$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          ARCH: ${{ matrix.arch }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-extended-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*

  extended-merge:
    needs: extended-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-extended-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create \
            --tag=zhongruoyu/buildpack-deps:extended \
            zhongruoyu/buildpack-deps:extended@sha256:"$(cat "$RUNNER_TEMP"/digests/x86_64)" \
            zhongruoyu/buildpack-deps:extended@sha256:"$(cat "$RUNNER_TEMP"/digests/aarch64)"
