name: Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      tag: base
      build-args: |
        GCC_VERSION
        GCC_SHA256
        MAKE_VERSION
        MAKE_SHA256
        LINUX_HEADERS_VERSION
        LINUX_HEADERS_SHA256
        BINUTILS_VERSION
        BINUTILS_SHA256

  extended:
    needs: base
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      tag: extended
      build-args: |
        ZLIB_VERSION
        ZLIB_SHA256
        OPENSSL_VERSION
        OPENSSL_SHA256
        CURL_VERSION
        CURL_SHA256
        GIT_VERSION
        GIT_SHA256
        CMAKE_VERSION
        CMAKE_SHA256
        PYTHON_VERSION
        PYTHON_SHA256
