name: Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  DOCKERHUB_REPOSITORY: zhongruoyu/buildpack-deps
  GCC_VERSION: "14.2.0"
  MAKE_VERSION: "4.4.1"
  LINUX_HEADERS_VERSION: "6.6.58"
  BINUTILS_VERSION: "2.43.1"
  ZLIB_VERSION: "1.3.1"
  OPENSSL_VERSION: "3.4.0"
  CURL_VERSION: "8.10.1"
  GIT_VERSION: "2.47.0"
  CMAKE_VERSION: "3.30.5"
  PYTHON_VERSION: "3.13.0"

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: zhongruoyu/buildpack-deps:base
          file: Dockerfile.base
          build-args: |
            GCC_VERSION=${{ env.GCC_VERSION }}
            MAKE_VERSION=${{ env.MAKE_VERSION }}
            LINUX_HEADERS_VERSION=${{ env.LINUX_HEADERS_VERSION }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
          push: true

  extended:
    needs: base
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: zhongruoyu/buildpack-deps:extended
          file: Dockerfile.extended
          build-args: |
            ZLIB_VERSION=${{ env.ZLIB_VERSION }}
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}
            CURL_VERSION=${{ env.CURL_VERSION }}
            GIT_VERSION=${{ env.GIT_VERSION }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          push: true
