name: Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GCC_VERSION: "14.2.0"
  GCC_SHA256: "7d376d445f93126dc545e2c0086d0f647c3094aae081cdb78f42ce2bc25e7293"
  MAKE_VERSION: "4.4.1"
  MAKE_SHA256: "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
  LINUX_HEADERS_VERSION: "6.6.58"
  LINUX_HEADERS_SHA256: "4e9b1e3f8a9a411565c68456fc50127ea71a1be24c05a203c5cebbfa52ab1d69"
  BINUTILS_VERSION: "2.43.1"
  BINUTILS_SHA256: "e4c38b893f590853fbe276a6b8a1268101e35e61849a07f6ee97b5ecc97fbff8"
  ZLIB_VERSION: "1.3.1"
  ZLIB_SHA256: "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"
  OPENSSL_VERSION: "3.4.0"
  OPENSSL_SHA256: "e15dda82fe2fe8139dc2ac21a36d4ca01d5313c75f99f46c4e8a27709b7294bf"
  CURL_VERSION: "8.10.1"
  CURL_SHA256: "d15ebab765d793e2e96db090f0e172d127859d78ca6f6391d7eafecfd894bbc0"
  GIT_VERSION: "2.47.0"
  GIT_SHA256: "a84a7917e0ab608312834413f01fc01edc7844f9f9002ba69f3b4f4bcb8d937a"
  CMAKE_VERSION: "3.30.5"
  CMAKE_SHA256: "9f55e1a40508f2f29b7e065fa08c29f82c402fa0402da839fffe64a25755a86d"
  PYTHON_VERSION: "3.13.0"
  PYTHON_SHA256: "12445c7b3db3126c41190bfdc1c8239c39c719404e844babbd015a1bc3fafcd4"

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: zhongruoyu/buildpack-deps:base
          file: ${{ matrix.arch }}/Dockerfile.base
          build-args: |
            GCC_VERSION=${{ env.GCC_VERSION }}
            GCC_SHA256=${{ env.GCC_SHA256 }}
            MAKE_VERSION=${{ env.MAKE_VERSION }}
            MAKE_SHA256=${{ env.MAKE_SHA256 }}
            LINUX_HEADERS_VERSION=${{ env.LINUX_HEADERS_VERSION }}
            LINUX_HEADERS_SHA256=${{ env.LINUX_HEADERS_SHA256 }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            BINUTILS_SHA256=${{ env.BINUTILS_SHA256 }}
          push: true

  extended:
    needs: base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: zhongruoyu/buildpack-deps:extended
          file: ${{ matrix.arch }}/Dockerfile.extended
          build-args: |
            ZLIB_VERSION=${{ env.ZLIB_VERSION }}
            ZLIB_SHA256=${{ env.ZLIB_SHA256 }}
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}
            OPENSSL_SHA256=${{ env.OPENSSL_SHA256 }}
            CURL_VERSION=${{ env.CURL_VERSION }}
            CURL_SHA256=${{ env.CURL_SHA256 }}
            GIT_VERSION=${{ env.GIT_VERSION }}
            GIT_SHA256=${{ env.GIT_SHA256 }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            CMAKE_SHA256=${{ env.CMAKE_SHA256 }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_SHA256=${{ env.PYTHON_SHA256 }}
          push: true
